---
- block:
    - name: Install ntp package
      ansible.builtin.package:
        name: ntp
        state: present
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      environment: "{{ proxy_env | default({}) }}"
      tags: ntp_install

    - name: Copy the ntp.conf file
      ansible.builtin.template:
        src: ntp.conf.j2
        dest: /etc/ntp.conf
      notify: "restart ntp"
      when: ansible_os_family == "Debian"
      tags: ntp_conf

  when: ntp_enabled is defined and ntp_enabled|bool
  tags: ntp

...
