---

- name: Check if postgresql.conf exists
  ansible.builtin.stat:
    path: "{{ postgresql_conf_dir }}.postgresql.conf"
    register: postgresql_conf_stat
  become: true
  become_user: postgres

- name: Fail if postgresql.conf doesn't exist
  ansible.builtin.fail:
    msg: "File {{ postgresql_conf_dir }}.postgresql.conf does not exist!"
  when: postgresql_conf_stat.stat.exists == false

  - name: Check if postgresql.base.conf exists
  ansible.builtin.stat:
    path: "{{ postgresql_conf_dir }}.postgresql.base.conf"
    register: postgresql_conf_stat
  become: true
  become_user: postgres

- name: Fail if postgresql.base.conf doesn't exist
  ansible.builtin.fail:
    msg: "File {{ postgresql_conf_dir }}.postgresql.conf does not exist!"
  when: postgresql_conf_stat.stat.exists == false

- name: Get existing postgresql parameters
  ansible.builtin.lineinfile:
    path: "{{ postgresql_conf_dir }}.postgresql.conf"
    regexp: '^.*([^:]+): .*$'
    state: present
    register: postgresql_parameters_existing
  become: true
  become_user: postgres

- name: Get postgresql.conf content
  ansible.builtin.file:
    path: "{{ postgresql_conf_dir }}.postgresql.conf"
    content: "{{ lookup('file', postgresql_conf_dir }}.postgresql.conf') }}"
    register: postgresql_conf_content

- name: Add new postgresql parameters to "{{ postgresql_conf_dir }}.postgresql.conf"
  ansible.builtin.lineinfile:
    path: "{{ postgresql_conf_dir }}.postgresql.conf"
    line: "{{ item.option }}: {{ item.value }}"
    insertbefore: "{{ lookup('regex_findall', '^.*' ~ item.option ~ ':.*$', postgresql_conf_content) | first }}"
  loop: "{{ postgresql_parameters }}"
  when: item.option not in postgresql_parameters_existing.lines

- name: Update postgresql parameters from "{{ postgresql_conf_dir }}.postgresql.conf"
  ansible.builtin.lineinfile:
    path: "{{ postgresql_conf_dir }}.postgresql.conf"
    regexp: '^.*{{ item.option }}: {{ item.value }}$'
    state: absent
  loop: "{{ postgresql_parameters }}"
  when: item.value == "null"

- name: Replace postgresql parameter in "{{ postgresql_conf_dir }}.postgresql.conf"
  ansible.builtin.replace:
    path: "{{ postgresql_conf_dir }}.postgresql.conf"
    regexp: '^.*{{ item.option }}: {{ item.value }}$'
    replace: '^.*{{ item.option }}: {{ item.value }}$'
    with_string: '{{ item.option }}: {{ expected_value }}'
  loop: "{{ postgresql_parameters }}"
  when: item.value != "{{ expected_value }}"

- name: Delete postgresql parameters from "{{ postgresql_conf_dir }}.postgresql.conf"
  ansible.builtin.lineinfile:
    path: "{{ postgresql_conf_dir }}.postgresql.conf"
    regexp: '^.*{{ item.option }}: {{ item.value }}$'
    state: absent
  loop: "{{ postgresql_parameters }}"
  when: item.value == "null"

# Update pg_hba.conf
- ansible.builtin.import_tasks: pg_hba.yml

- name: "Check if there are any changed parameters that require a restart"
  become: true
  become_user: postgres
  community.postgresql.postgresql_query:
    login_host: "127.0.0.1"
    login_port: "{{ postgresql_port }}"
    login_user: "{{ patroni_superuser_username }}"
    login_password: "{{ patroni_superuser_password }}"
    login_db: "postgres"
    query: "select name from pg_settings where pending_restart is true"
  register: pending_restart_result

- name: "Set pg_pending_restart_settings variable"
  ansible.builtin.set_fact:
    pg_pending_restart_settings: "{{ pending_restart_result.query_result }}"

- name: "Display parameters requiring PostgreSQL restart"
  ansible.builtin.debug:
    msg:
      - "On server {{ ansible_hostname }}, the following parameters have changed and require PostgreSQL to restart:"
      - "{{ pg_pending_restart_settings | map(attribute='name') | list }}"
  when: pg_pending_restart_settings | length > 0
...