---
- block:
    - name: Add PostgreSQL repo
      shell: echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
      become: yes
      changed_when: false

    - name: Add key PostgreSQL repo
      ansible.builtin.apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present
      become: yes

    - name: Add TimescaleDB for PostgreSQL repo
      shell: echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -c -s) main" > /etc/apt/sources.list.d/timscale.list
      become: yes
      when: install_timescaledb|bool
      changed_when: false

    - name: Add key repo TimescaleDB
      apt_key:
        url: "https://packagecloud.io/timescale/timescaledb/gpgkey"
        state: present
      become: yes
      when: install_timescaledb|bool

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3

  environment: "{{ proxy_env | default({}) }}"
  tags: add_repo
