---

- name: Setting kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop: "{{ sysctl_conf }}"
  when: sysctl_set|bool
  ignore_errors: true  
  tags: sysctl, kernel

...