---

- name: Checking ansible version
  ansible.builtin.fail:
    msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
  delegate_to: localhost
  when:
    - ansible_version.full is version(minimal_ansible_version, '<')

- name: Checking Linux distribution
  ansible.builtin.fail:
    msg: "{{ ansible_distribution }} is not supported"
  when: ansible_distribution not in os_valid_distributions

- name: Checking version of OS Linux
  ansible.builtin.fail:
    msg: "{{ ansible_distribution_version }} of {{ ansible_distribution }} is not supported"
  when: ansible_distribution_version is version_compare(os_minimum_versions[ansible_distribution], '<')

#- name: Perform pre-checks for pgbouncer
#  ansible.builtin.import_tasks: pgbouncer.yml
#  when:
#    - pgbouncer_install is defined
#    - pgbouncer_install | bool

- name: Perform pre-checks for postgresql
  ansible.builtin.import_tasks: postgresql.yml

...

